"""Tests for BaseExchange contract: candle pagination, sync wrappers, defaults."""

from __future__ import annotations

import pytest

from pycex.base import BaseExchange
from pycex.exceptions import NotSupportedError
from pycex.models import Candle


class Fake(BaseExchange):
    name = "fake"
    candle_page_limit = 2

    def __init__(self) -> None:
        self.calls: list[tuple] = []

    def to_native(self, symbol: str) -> str:
        return symbol.replace("/", "")

    def from_native(self, native: str) -> str:
        return native[:3] + "/" + native[3:]

    async def _fetch_candles_page(self, native, timeframe, *, since, until, limit):
        self.calls.append((since, until, limit))
        start = -(-(since or 0) // 60_000) * 60_000  # 분 경계로 올림 정렬
        return [Candle(timestamp=start + i * 60_000, open=1, high=1, low=1, close=1, volume=1) for i in range(limit)]

    # 나머지 추상 메서드는 NotSupportedError 로 채움
    async def fetch_ticker(self, symbol):
        raise NotSupportedError

    async def fetch_order_book(self, symbol, *, limit=20):
        raise NotSupportedError

    async def fetch_trades(self, symbol, *, limit=100):
        raise NotSupportedError

    async def fetch_markets(self):
        raise NotSupportedError

    async def fetch_balance(self):
        raise NotSupportedError

    async def create_order(self, symbol, side, order_type, amount, price=None):
        raise NotSupportedError

    async def cancel_order(self, order_id, symbol):
        raise NotSupportedError

    async def fetch_order(self, order_id, symbol):
        raise NotSupportedError

    async def fetch_open_orders(self, symbol=None):
        raise NotSupportedError

    async def fetch_my_trades(self, symbol=None, *, since=None, limit=None):
        raise NotSupportedError

    async def close(self) -> None:
        pass


async def test_candles_paginate_since_until() -> None:
    ex = Fake()
    out = await ex.fetch_candles("BTC/USDT", "1m", since=0, until=4 * 60_000)
    assert [c.timestamp for c in out] == [0, 60_000, 120_000, 180_000, 240_000]
    assert len(ex.calls) == 3  # 2+2+1 (마지막 페이지는 until 도달)


async def test_candles_single_page_without_since() -> None:
    ex = Fake()
    await ex.fetch_candles("BTC/USDT", "1m", limit=2)
    assert ex.calls == [(None, None, 2)]


async def test_unsupported_timeframe() -> None:
    with pytest.raises(NotSupportedError):
        await Fake().fetch_candles("BTC/USDT", "3m")


def test_sync_wrapper_autogenerated() -> None:
    ex = Fake()
    out = ex.fetch_candles_sync("BTC/USDT", "1m", limit=2)
    assert len(out) == 2


async def test_sync_wrapper_inside_loop_raises() -> None:
    with pytest.raises(RuntimeError):
        Fake().fetch_candles_sync("BTC/USDT", "1m", limit=1)


async def test_positions_default_not_supported() -> None:
    with pytest.raises(NotSupportedError):
        await Fake().fetch_positions()
