"""Tests for BaseExchange contract: candle pagination, sync wrappers, defaults."""

from __future__ import annotations

import asyncio
import inspect
import re

import pytest

from pycex.base import _SYNC_TARGETS, BaseExchange
from pycex.exceptions import NotSupportedError
from pycex.http import HTTPClient
from pycex.models import Candle


class Fake(BaseExchange):
    name = "fake"
    candle_page_limit = 2

    def __init__(self) -> None:
        self.calls: list[tuple] = []

    def to_native(self, symbol: str) -> str:
        return symbol.replace("/", "")

    def from_native(self, native: str) -> str:
        return native[:3] + "/" + native[3:]

    async def _fetch_candles_page(self, native, timeframe, *, since, until, limit):
        self.calls.append((since, until, limit))
        start = -(-(since or 0) // 60_000) * 60_000  # 분 경계로 올림 정렬
        return [Candle(timestamp=start + i * 60_000, open=1, high=1, low=1, close=1, volume=1) for i in range(limit)]

    # 나머지 추상 메서드는 NotSupportedError 로 채움
    async def fetch_ticker(self, symbol):
        raise NotSupportedError

    async def fetch_order_book(self, symbol, *, limit=20):
        raise NotSupportedError

    async def fetch_trades(self, symbol, *, limit=100):
        raise NotSupportedError

    async def fetch_markets(self):
        raise NotSupportedError

    async def fetch_balance(self):
        raise NotSupportedError

    async def create_order(self, symbol, side, order_type, amount, price=None):
        raise NotSupportedError

    async def cancel_order(self, order_id, symbol):
        raise NotSupportedError

    async def fetch_order(self, order_id, symbol):
        raise NotSupportedError

    async def fetch_open_orders(self, symbol=None):
        raise NotSupportedError

    async def fetch_my_trades(self, symbol=None, *, since=None, limit=None):
        raise NotSupportedError


async def test_candles_paginate_since_until() -> None:
    ex = Fake()
    out = await ex.fetch_candles("BTC/USDT", "1m", since=0, until=4 * 60_000)
    assert [c.timestamp for c in out] == [0, 60_000, 120_000, 180_000, 240_000]
    assert len(ex.calls) == 3  # 2+2+1 (마지막 페이지는 until 도달)


async def test_candles_single_page_without_since() -> None:
    ex = Fake()
    await ex.fetch_candles("BTC/USDT", "1m", limit=2)
    assert ex.calls == [(None, None, 2)]


async def test_unsupported_timeframe() -> None:
    with pytest.raises(NotSupportedError):
        await Fake().fetch_candles("BTC/USDT", "3m")


def test_sync_wrapper_autogenerated() -> None:
    ex = Fake()
    out = ex.fetch_candles_sync("BTC/USDT", "1m", limit=2)
    assert len(out) == 2


async def test_sync_wrapper_inside_loop_raises() -> None:
    with pytest.raises(RuntimeError):
        Fake().fetch_candles_sync("BTC/USDT", "1m", limit=1)


async def test_positions_default_not_supported() -> None:
    with pytest.raises(NotSupportedError):
        await Fake().fetch_positions()


class BackwardFake(Fake):
    """Models a venue that only pages **backward**: it ignores ``since`` entirely and
    serves the newest ``limit`` bars at or before ``until`` (``until=None`` = now),
    newest-first — the shape of Upbit/Bithumb (``to``), Korbit (``end``), OKX
    (``after``) and Bitget spot (``endTime``).

    The old forward-only loop re-served the same newest page on every iteration
    here, found no new timestamps and broke out after one page — silently
    truncating every multi-page range on five of the seven adapters.
    """

    NOW = 10 * 60_000

    async def _fetch_candles_page(self, native, timeframe, *, since, until, limit):
        self.calls.append((since, until, limit))
        end = self.NOW if until is None else until
        bars = [t for t in range(0, self.NOW + 60_000, 60_000) if t <= end]
        newest_first = sorted(bars, reverse=True)[:limit]
        return [Candle(timestamp=t, open=1, high=1, low=1, close=1, volume=1) for t in newest_first]


class ShortPageFake(Fake):
    """Models Bybit: the venue answers a ``since`` cursor with a page whose oldest bar
    sits just *before* the cursor, so after the base loop's range filter the page is
    always one bar shorter than ``candle_page_limit``. The old
    ``len(page) < candle_page_limit`` early break read that as "last page" and
    truncated the result at the first page (live: 199 of 500 bars on Bybit)."""

    async def _fetch_candles_page(self, native, timeframe, *, since, until, limit):
        self.calls.append((since, until, limit))
        start = -(-(since or 0) // 60_000) * 60_000 - 60_000
        return [Candle(timestamp=start + i * 60_000, open=1, high=1, low=1, close=1, volume=1) for i in range(limit)]


def test_candle_paging_defaults_to_forward() -> None:
    assert BaseExchange.candle_paging == "forward"
    assert Fake().candle_paging == "forward"


async def test_backward_paging_walks_a_multi_page_span() -> None:
    ex = BackwardFake()
    ex.candle_paging = "backward"
    out = await ex.fetch_candles("BTC/USDT", "1m", since=0, until=4 * 60_000)
    assert [c.timestamp for c in out] == [0, 60_000, 120_000, 180_000, 240_000]
    assert len(ex.calls) == 3  # 2 + 2 + 1 bars over a page limit of 2
    # cursor walks down via `until`: page1 = [240k, 180k] -> 179_999, page2 = [120k, 60k] -> 59_999
    assert [c[1] for c in ex.calls] == [4 * 60_000, 3 * 60_000 - 1, 60_000 - 1]
    assert all(c[0] is None for c in ex.calls)  # `since` is never the cursor on a backward venue


async def test_backward_paging_without_until_anchors_at_now() -> None:
    ex = BackwardFake()
    ex.candle_paging = "backward"
    out = await ex.fetch_candles("BTC/USDT", "1m", since=7 * 60_000)
    assert [c.timestamp for c in out] == [7 * 60_000, 8 * 60_000, 9 * 60_000, 10 * 60_000]
    assert ex.calls[0][1] is None  # first page anchors at the venue's "now"


async def test_backward_paging_with_limit_bounds_the_anchor() -> None:
    """A `limit` must not make the walk start at "now" and page all the way down —
    the anchor is bounded to `since + limit * timeframe`."""
    ex = BackwardFake()
    ex.candle_paging = "backward"
    out = await ex.fetch_candles("BTC/USDT", "1m", since=0, limit=3)
    assert [c.timestamp for c in out] == [0, 60_000, 120_000]
    assert ex.calls[0][1] == 3 * 60_000


async def test_forward_paging_survives_a_short_in_range_page() -> None:
    ex = ShortPageFake()
    out = await ex.fetch_candles("BTC/USDT", "1m", since=0, until=4 * 60_000)
    assert [c.timestamp for c in out] == [0, 60_000, 120_000, 180_000, 240_000]


def test_close_sync_closes_the_async_client() -> None:
    """`close_sync()`/`__exit__` used to close a second, never-used httpx.Client and
    leave the AsyncClient — the one every sync wrapper actually drives through
    asyncio.run — open."""
    ex = Fake()
    ex._http = HTTPClient("https://example.invalid")
    client = ex._http._client  # 클라이언트는 지연 생성이므로 먼저 실체화한다
    with ex:
        pass
    assert client.is_closed
    assert ex._http._client_obj is client  # 닫힌 사실이 남아야 다음 호출이 새로 만든다


def test_close_sync_inside_running_loop_raises() -> None:
    async def _run() -> None:
        ex = Fake()
        ex._http = HTTPClient("https://example.invalid")
        with pytest.raises(RuntimeError):
            ex.close_sync()
        await ex._http.close()

    asyncio.run(_run())


def test_type_checking_sync_stubs_cover_every_sync_target() -> None:
    """The TYPE_CHECKING block is hand-written while the runtime twins come from
    __init_subclass__; a new entry in _SYNC_TARGETS must not silently ship without
    a stub (mypy would then reject a call the runtime supports, and vice versa)."""
    block = inspect.getsource(BaseExchange).split("if TYPE_CHECKING:")[1].split("def __init_subclass__")[0]
    stubbed = set(re.findall(r"def (\w+)_sync\(", block))
    assert stubbed == set(_SYNC_TARGETS)
    ex = Fake()
    assert all(callable(getattr(ex, f"{n}_sync")) for n in _SYNC_TARGETS)
